// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindTrack.Infrastructure.Data;

#nullable disable

namespace MindTrack.Migrations
{
    [DbContext(typeof(MindTrackContext))]
    partial class MindTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MindTrack.Domain.Models.HeartMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<double?>("Rmssd")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HeartMetrics");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Concluida")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.StressScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("SourceMetricId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceMetricId");

                    b.HasIndex("UserId");

                    b.ToTable("StressScores");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<int?>("MetaId")
                        .HasColumnType("int");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.HasIndex("UserId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.HeartMetric", b =>
                {
                    b.HasOne("MindTrack.Domain.Models.User", "User")
                        .WithMany("HeartMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.Meta", b =>
                {
                    b.HasOne("MindTrack.Domain.Models.User", "User")
                        .WithMany("Metas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.StressScore", b =>
                {
                    b.HasOne("MindTrack.Domain.Models.HeartMetric", "SourceMetric")
                        .WithMany()
                        .HasForeignKey("SourceMetricId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MindTrack.Domain.Models.User", "User")
                        .WithMany("StressScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMetric");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.Tarefa", b =>
                {
                    b.HasOne("MindTrack.Domain.Models.Meta", "Meta")
                        .WithMany("Tarefas")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MindTrack.Domain.Models.User", "User")
                        .WithMany("Tarefas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.Meta", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("MindTrack.Domain.Models.User", b =>
                {
                    b.Navigation("HeartMetrics");

                    b.Navigation("Metas");

                    b.Navigation("StressScores");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
